export const GET_DOCTORS_LIST = "GET_DOCTORS_LIST";
export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS";
export const CHOOSE_DOCTOR = "CHOOSE_DOCTOR";
export const CHECK_HOURS = "CHECK_HOURS";
